### ISSUE TITLE
Fatal error: Call to undefined function imagettfbbox()

### ISSUE THREAD

**Issue by skrimp** [vasile/GTFS-viz#13]
Hi there, I'm trying to run the last part of the "Visualize" (`rake project:deploy`) section and am running into the following error:

```
users-MacBook-Pro:GTFS-viz user$ rake project:deploy --trace
** Invoke project:deploy (first_time)
** Execute project:deploy
rm -rf /Users/user/Dropbox/GTFS-viz/transit-map-master/api/geojson/*
rm -rf /Users/user/Dropbox/GTFS-viz/transit-map-master/api/gtfs-data
mkdir /Users/user/Dropbox/GTFS-viz/transit-map-master/api/gtfs-data
cp /Users/user/GD/GTFS-viz/tmp/tucson/gtfs.db /Users/user/Dropbox/GTFS-viz/transit-map-master/api/gtfs-data/gtfs.db
cp /Users/user/GD/GTFS-viz/tmp/tucson/gtfs_shapes.geojson /Users/user/Dropbox/GTFS-viz/transit-map-master/api/geojson/gtfs_shapes.geojson
cp /Users/user/GD/GTFS-viz/tmp/tucson/gtfs_stops.geojson /Users/user/Dropbox/GTFS-viz/transit-map-master/api/geojson/gtfs_stops.geojson
rm -rf /Users/user/Dropbox/GTFS-viz/transit-map-master/api/tmp && mkdir /Users/user/Dropbox/GTFS-viz/transit-map-master/api/tmp && chmod 0777 /Users/user/Dropbox/GTFS-viz/transit-map-master/api/tmp
mkdir -p /Users/user/Dropbox/GTFS-viz/transit-map-master/api/tmp/cache/db && chmod 0777 /Users/user/Dropbox/GTFS-viz/transit-map-master/api/tmp/cache/db
** Invoke project:update_settings_ft (first_time)
** Execute project:update_settings_ft
** Invoke project:update_settings_map (first_time)
** Execute project:update_settings_map
** Invoke project:update_settings_routes (first_time)
** Execute project:update_settings_routes
rm -f /Users/user/Dropbox/GTFS-viz/transit-map-master/static/images/route_icons/*.png
php /Users/user/Dropbox/GTFS-viz/transit-map-route-icon-master/route_icon.php bg=FFD457 fg=000000 t="1"

Fatal error: Call to undefined function imagettfbbox() in /Users/user/Dropbox/GTFS-viz/transit-map-route-icon-master/route_icon.php on line 69
rake aborted!
Command failed with status (255): [php /Users/user/Dropbox/GTFS-viz/trans...]
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
/Users/user/GD/GTFS-viz/Rakefile:543:in `block (3 levels) in <top (required)>'
/Users/user/GD/GTFS-viz/Rakefile:528:in `each'
/Users/user/GD/GTFS-viz/Rakefile:528:in `block (2 levels) in <top (required)>'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/user/GD/GTFS-viz/Rakefile:431:in `block (2 levels) in <top (required)>'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/user/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/user/.rvm/rubies/ruby-2.2.3/bin/rake:33:in `<main>'
/Users/user/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => project:update_settings_routes
```

Do you have any advice on how I could handle this?

**Comment by vasile** [comment]
Yeah, is the PHP and GD library support
Can you post somwehere the result of your `phpinfo();` ?

**Comment by skrimp** [comment]
Hi Vasile, thanks for the response.  I'm not quite sure what you mean, though.  I'm not running this inside of a PHP app, so I'm not quite sure how I could use phpinfo(); to debug...do you mind telling me what you mean by that?  Thank you!

**Comment by reelman** [comment]
Hi Skrimp,
Just bumped into the same issue. If you are using PHP build in OS X then please update by brew.
