### ISSUE TITLE
rake aborted! LoadError: cannot load such file -- google/api_client

### ISSUE THREAD

**Issue by ghost** [vasile/GTFS-viz#20]
I can't make the script work, I did "bundle install" and all ruby gems are installed.

here is the log:

rake setup:init --trace
rake aborted!
LoadError: cannot load such file -- google/api_client
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/home/ubuntu/app/transit-map/GTFS-viz/inc/ft.rb:3:in `<top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/default_loader.rb:11:in `load'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:788:in `load_imports'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:718:in `raw_load_rakefile'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

**Comment by Ge-Rag** [comment]
In your inc/ft.rb
Change 
require 'google/client_api'
to
require 'google/apis'
Worked for me.
