### ISSUE TITLE
Cannot convert files

### ISSUE THREAD

**Issue by renjum** [vasile/GTFS-viz#7]
Hi,

I followed all the steps but I am stuck towards the end :(
I tried to populate the fusion tables by running the following command:

Command:
rake project:deploy_fusiontables 

Resonse:
rake aborted!
cannot load such file -- fusion_tables
Tasks: TOP => project:deploy_fusiontables

Do I need a connection to Google to perform this task behind the firewall?
Any help is appreciated. Thanks!

System: Redhat EL6 and Ruby 1.9x

The detailed error is:

** Invoke project:deploy_fusiontables (first_time)
** Execute project:deploy_fusiontables
rake aborted!
cannot load such file -- fusion_tables
/usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/tmscent/ruby/GTFS/Rakefile:431:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/1.9.1/rake/task.rb:205:in `call'
/usr/local/lib/ruby/1.9.1/rake/task.rb:205:in `block in execute'
/usr/local/lib/ruby/1.9.1/rake/task.rb:200:in `each'
/usr/local/lib/ruby/1.9.1/rake/task.rb:200:in `execute'
/usr/local/lib/ruby/1.9.1/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/1.9.1/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.9.1/rake/task.rb:144:in `invoke'
/usr/local/lib/ruby/1.9.1/rake/application.rb:116:in `invoke_task'
/usr/local/lib/ruby/1.9.1/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/local/lib/ruby/1.9.1/rake/application.rb:94:in `each'
/usr/local/lib/ruby/1.9.1/rake/application.rb:94:in `block in top_level'
/usr/local/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/lib/ruby/1.9.1/rake/application.rb:88:in `top_level'
/usr/local/lib/ruby/1.9.1/rake/application.rb:66:in `block in run'
/usr/local/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling'
/usr/local/lib/ruby/1.9.1/rake/application.rb:63:in `run'
/usr/local/bin/rake:32:in `<main>'
Tasks: TOP => project:deploy_fusiontables

Regards
Renju

**Comment by renjum** [comment]
Installed ruby gem fusion_tables
